from snakemake.shell import shell


float_advtmp=[1, 0.1]
bool_condprob=['no', 'yes']
int_negsam=[32, 64]


rule all:
    input:
      expand("log/advTmp{advtmp}_condProb_{condprob}_negSamp_{negsam}.log", 
             negsam = int_negsam, condprob = bool_condprob, advtmp = float_advtmp
      )


rule run_gridsearch:
    #conda: "conda-envs/nbfnet.yml"
    resources: partition="gpu_p", cpus=1, mem="32G", time="12:00:00",  gres="gpu:1", qos="gpu", exclude="gpusrv[12,15,17,22-23,25,26-30]"
    input:
        "../../../config/knowledge_graph/primekg/adrenal_gland.yaml"
    output:
        "log/advTmp{advtmp}_condProb_{condprob}_negSamp_{negsam}.log"
    params:
        negsam=lambda wildcards: wildcards.negsam,
        advtmp=lambda wildcards: wildcards.advtmp,
        condprob=lambda wildcards: wildcards.condprob
    shell:
        """
        . /home/icb/yue.hu/proj_genefun/conda-env/activate_env.sh; touch log/advTmp{params.advtmp}_condProb_{params.condprob}_negSamp_{params.negsam}.log; python ../../../script/run.py -c {input} --gpus [0] --version v1 --adv_tmp {params.advtmp} --cond_prob {params.condprob} --neg_samp {params.negsam}
        """

