output_dir: experiments/

dataset:
  class: biomedical
  path: data/mock
  include_factgraph: yes
  
task:
  class: KnowledgeGraphCompletionBiomed
  model:
    class: TransE
    embedding_dim: 512
    max_score: 6
  criterion: bce
  num_negative: 512
  strict_negative: yes
  heterogeneous_negative: yes
  heterogeneous_evaluation: yes
  adversarial_temperature: 1
  sample_weight: yes
  full_batch_eval: no

optimizer:
  class: Adam
  lr: 5.0e-4

engine:
  gpus: {{ gpus }}
  batch_size: 1024

train:
  num_epoch: 500

metric: mrr