output_dir: experiments/

dataset:
  class: biomedical
  path: data/mock
  include_factgraph: yes
  files: ['train1.txt', 'train2.txt', 'valid.txt', 'test_vis.txt']

task:
  class: KnowledgeGraphCompletionBiomed
  model:
    class: NBFNet
    input_dim: 32
    hidden_dims: [32, 32, 32, 32, 32, 32]
    message_func: distmult
    aggregate_func: pna
    short_cut: yes
    layer_norm: yes
    dependent: yes
    symmetric: yes
  criterion: bce
  num_negative: 32
  strict_negative: yes
  adversarial_temperature: 0.5
  sample_weight: no
  heterogeneous_negative: yes
  heterogeneous_evaluation: yes
  conditional_probability: yes
  full_batch_eval: no
  remove_pos: no

optimizer:
  class: Adam
  lr: 5.0e-3

engine:
  gpus: {{ gpus }}
  batch_size: 4
  

train:
  num_epoch: 5
  
metric: mrr

checkpoint: {{checkpoint}}
