from snakemake.shell import shell


float_advtmp=[0.5]
bool_condprob=['yes']
int_negsam=[32]
str_aggfun = ["pna"]



rule all:
    input:
      expand("log/advTmp{advtmp}_condProb_{condprob}_negSamp_{negsam}_aggFun_{aggfun}.log", 
             negsam = int_negsam, condprob = bool_condprob, advtmp = float_advtmp, aggfun = str_aggfun
      )


rule run_gridsearch:
    #conda: "conda-envs/nbfnet.yml"
    resources: partition="gpu_p", cpus=1, mem="32G", time="12:00:00",  gres="gpu:1", qos="gpu", nodelist="gpusrv62" #, exclude="gpusrv[12,15,17,22-23,25,26-30],supergpu[02-03,05,07-08]"
    input:
        "../../../config/knowledge_graph/primekg/cardiovascular.yaml"
    output:
        "log/advTmp{advtmp}_condProb_{condprob}_negSamp_{negsam}_aggFun_{aggfun}.log"
    params:
        negsam=lambda wildcards: wildcards.negsam,
        advtmp=lambda wildcards: wildcards.advtmp,
        condprob=lambda wildcards: wildcards.condprob,
	aggfun=lambda wildcards: wildcards.aggfun
    shell:
        """
        . /home/icb/yue.hu/proj_genefun/conda-env/activate_env.sh; touch log/advTmp{params.advtmp}_condProb_{params.condprob}_negSamp_{params.negsam}_aggFun_{params.aggfun}.log; python ../../../script/run.py -c {input} --gpus [0] --version v1 --adv_tmp {params.advtmp} --cond_prob {params.condprob} --neg_samp {params.negsam} --agg_fun {params.aggfun}
        """

