output_dir: BioPathNet/experiments/

dataset:
  class: biomedical
  path: BioPathNet/data/PC_KEGG_0602
  include_factgraph: yes
  
task:
  class: KnowledgeGraphCompletionBiomed
  model:
    class: NBFNet
    input_dim: 32
    hidden_dims: [32, 32, 32, 32, 32, 32]
    message_func: distmult
    aggregate_func: pna
    short_cut: yes
    layer_norm: yes
    remove_one_hop: yes
    dependent: yes
  criterion: bce
  num_negative: 32
  strict_negative: yes
  adversarial_temperature: 1
  sample_weight: no
  heterogeneous_negative: yes
  heterogeneous_evaluation: yes
  full_batch_eval: yes


optimizer:
  class: Adam
  lr: 5.0e-3

engine:
  gpus: {{ gpus }}
  batch_size: 32
  

train:
  num_epoch: 15
  #batch_per_epoch: 500
  
metric: mrr
